### ISSUE TITLE
CI needed

### ISSUE THREAD

**Issue by mfkasim1** [mfkasim1/xitorch#2]
Continuous Integration needs to be set up (at least running the tests automatically)

**Comment by AdityaJ7** [comment]
Hey @mfkasim91 I would like to solve this issue for you.

**Comment by mfkasim91** [comment]
Sure, please go ahead

**Comment by AdityaJ7** [comment]
> Sure, please go ahead

Hey just wanted to know you want flask8 and pytest included right? and what python versions should I include in testing or should it just be the latest version

**Comment by mfkasim91** [comment]
I have no dependency on flask8, but I can add it if needed.
pytest is included.
For the Python version, should include versions higher than 3.6.
Thanks!

**Comment by AdityaJ7** [comment]
> I have no dependency on flask8, but I can add it if needed.
> pytest is included.
> For the Python version, should include versions higher than 3.6.
> Thanks!

Oh sorry it was a typo from my side I meant flake8 , alright will add pytest for versions above 3,6

**Comment by mfkasim1** [comment]
Hi @AdityaJ7, is there any update on this?
Thanks

**Comment by AdityaJ7** [comment]
> Hi @AdityaJ7, is there any update on this?
> Thanks

Yes, sorry my exams started, I will start again from tomorrow

**Comment by mfkasim1** [comment]
No worries. Good luck for your exams!

**Comment by AdityaJ7** [comment]
> > Hi @AdityaJ7, is there any update on this?
> > Thanks
> 
> Yes, sorry my exams started, I will start again from tomorrow



> No worries. Good luck for your exams!

Thanks

**Comment by mfkasim1** [comment]
Hi, I've seen you've done some work on this. Can I do pull request on your work?

**Comment by AdityaJ7** [comment]
> Hi, I've seen you've done some work on this. Can I do pull request on your work?

sure

**Comment by mfkasim1** [comment]
I've done it. Thanks for the CI!

**Comment by AdityaJ7** [comment]
> I've done it. Thanks for the CI!

Sorry for the delay

**Comment by mfkasim1** [comment]
The error is actually from my side. I use `torch.outer` which is only available in the pre-release version of PyTorch.

**Comment by AdityaJ7** [comment]
> The error is actually from my side. I use `torch.outer` which is only available in the pre-release version of PyTorch.

yes, I was getting this error that outer is not defined or something like that, well I am happy because it is fixed now.
